---
title: "Decomposition"
knitr: 
  opts_chunk: 
    dev: "ragg_png"
    fig.width: 7
    fig.height: 5
    dpi: 150
---

## Preparation

```{r}
#| label: setup
library(PRcalc)

data(jp_lower_2021)

obj1 <- prcalc(jp_lower_2021,
               m = c(8, 13, 19, 22, 17, 11, 21, 28, 11, 6, 20),
               method = "dt")

obj2 <- prcalc(jp_lower_2021,
               m = c(8, 13, 19, 23, 19, 11, 20, 29, 10, 5, 19),
               method = "dt")

obj3 <- prcalc(jp_lower_2021,
               m = c(8, 13, 19, 23, 19, 11, 20, 29, 10, 5, 19),
               method = "msl")

```

## Decomposition

### Using a `prcalc` object.

```{r}
decompose(obj1)
decompose(obj2)
decompose(obj3)
```

Different $\alpha$ also available. Default is 2.

```{r}
decompose(obj1, alpha = 0.5)
decompose(obj1, alpha = 1)
decompose(obj1, alpha = 1.5)
decompose(obj1, alpha = 2)
decompose(obj1, alpha = 3)
```

### Using a `list` object.

```{r}
votes <- data.frame(Party  = LETTERS[1:5],
                    Block1 = c(8600, 2940, 6729, 2072, 2153),
                    Block2 = c(16282, 4663, 9915, 2928, 2587),
                    Block3 = c(2172, 8239, 13911, 4441, 6175),
                    Block4 = c(25900, 8600, 16500, 5300, 8600))

seats <- data.frame(Party  = LETTERS[1:5],
                    Block1 = c(3, 1, 2, 1, 1),
                    Block2 = c(6, 2, 3, 1, 1),
                    Block3 = c(7, 3, 5, 1, 2),
                    Block4 = c(7, 2, 5, 2, 3))

custom_list <- list(votes, seats)

decompose(custom_list)
decompose(custom_list, alpha = -1, as_disprop = FALSE)
decompose(custom_list, alpha = 0, as_disprop = FALSE)
decompose(custom_list, alpha = 1)
```
