---
title: "Seat allocation"
knitr: 
  opts_chunk: 
    dev: "ragg_png"
    fig.width: 7
    fig.height: 5
    dpi: 150
---

```{r}
#| label: setup
library(PRcalc)
```

## Dataset

```{r}
#| label: dataset
# Japanese upper house election in 2019
data("jp_upper_2019")
jp_upper_2019

# Japanese lower house election in 2019
data("jp_lower_2021")
jp_lower_2021
```

## Calculation

```{r}
#| label: calculation
obj1 <- prcalc(jp_upper_2019, m = 50, method = "dt")
obj1

obj2 <- prcalc(jp_lower_2021, 
               m = c(8, 13, 19, 22, 17, 11, 21, 28, 11, 6, 20), 
               method = "dt")
obj2
```

## Printing

```{r}
#| label: print
obj3 <- prcalc(jp_lower_2021, 
               m = c(8, 13, 19, 22, 17, 11, 21, 28, 11, 6, 20), 
               method = "hare")

print(obj3, show_total = FALSE) # Hide `Total` column
print(obj3, prop = TRUE) # Show proportion
print(obj3, use_gt = TRUE) # use {gt} package
summary(obj3) # summarize
summary(obj3, prop = TRUE) # summarize with proprotion
```

## Visualization

```{r}
#| label: plot
plot(obj1)
plot(obj2)
# Output only some parties
plot(obj2, 
     subset_p = c("自民", "公明", "立憲", "維新", "共産", "国民"))
# Output only some district
plot(obj2, 
     subset_p = c("自民", "公明", "立憲", "維新", "共産", "国民"),
     subset_b = c("Tokyo", "Kinki")) 
# Divide the facet by parties
plot(obj2, 
     subset_p  = c("自民", "公明", "立憲", "維新", "共産", "国民"),
     subset_b = c("Tokyo", "Kinki"),
     by        = "party")
# 3-column
plot(obj2, 
     subset_p  = c("自民", "公明", "立憲", "維新", "共産", "国民"),
     subset_b = c("Tokyo", "Kinki"),
     by        = "party",
     facet_col = 3)
# Use different y-axis scales for each facet
plot(obj2, 
     subset_p  = c("自民", "公明", "立憲", "維新", "共産", "国民"),
     subset_b  = c("Tokyo", "Kinki"),
     by        = "party",
     facet_col = 3,
     free_y    = TRUE)
```
