---
title: "Import Dataset"
knitr: 
  opts_chunk: 
    dev: "ragg_png"
    fig.width: 7
    fig.height: 5
    dpi: 150
toc: true
---

```{r}
#| message: false
library(tidyverse)
library(PRcalc)
```

## Example 1: Electoral result

```{r}
data("jp_lower_2021_result")

jp_lower_2021_result

obj1 <- as_prcalc(jp_lower_2021_result,
                  region     = "Pref",
                  district   = "Party",
                  population = "Votes",
                  magnitude  = "Seats",
                  distinct_name = TRUE)

plot(obj1, 
     subset_p  = c("Jimin", "Komei", "Rikken", 
                   "Kyosan", "Ishin", "Kokumin"),
     facet_col = 3,
     angle     = 25)
```

## Example 2: Electoral district allocation (from `data.frame`)

```{r}
data("au_district_2010")

au_district_2010

obj2 <- as_prcalc(au_district_2010,
                  region     = "region",
                  district   = "district",
                  population = "electorates",
                  magnitude  = "magnitude")

obj2

decompose(obj2, alpha = 0, as_disprop = FALSE)
```

## Example 3: Electoral district allocation (from `.csv` file)

Sample dataset can be downloaded from [here](../data/sample_dataset.csv).

```{r}
#| error: true
obj3 <- read_prcalc("../data/sample_dataset.csv",
                    region     = "region",
                    district   = "district",
                    population = "electorates",
                    magnitude  = "magnitude")

index(obj3)
```

## Example 4: 

```{r}
data("br_district_2010")

head(br_district_2010)

# In Brazil, proportionality is followed as a principle, with the exception that there should be a minimum of eight (8) members and a maximum of seventy (70) members per state. (source: Wikipedia) 
obj4 <- br_district_2010 |> 
  mutate(region = "national") |> 
  as_prcalc(region        = "region",
            district      = "district",
            population    = "population",
            magnitude     = "magnitude",
            distinct_name = TRUE)

obj4

obj5 <- br_district_2010 |> 
  select(-magnitude) |> 
  prcalc(m = 513, method = "hn")

list(obj4, obj5) |> 
  compare() |> 
  plot(angle = 45)

list(index(obj4), index(obj5)) |> 
  compare() |> 
  print(use_gt = TRUE, hide_id = TRUE)
```
