# Generated by fusen: do not edit by hand

#' \code{index}ジェネリック関数
#' 
#' @param x \code{PRcalc}オブジェクト
#' @param ... Ignored
#'
#' @return
#' none
#' @export
#'
index <- function(x, ...) {
  UseMethod("index")
}

#' 各種指標の計算
#' 
#' @param x \code{PRcalc}オブジェクト
#' @param ... Ignored
#'
#' @importFrom dplyr select
#' @importFrom dplyr pull
#' @importFrom dplyr last_col
#'
#' @return
#' A \code{PRcalc_index} object.
#' @export
#'
index.PRcalc <- function (x, ...) {
  
  Vote <- NULL
  
  Index_list <- NULL
  Index_list <- list()
  
  vote <- pull(select(x$VoteShare, Vote = last_col()), Vote)
  seat <- pull(select(x$SeatShare, Vote = last_col()), Vote)
  
  VS_df <- Rae_V <- Dhondt_V <- vote
  SS_df <- Rae_S <- Dhondt_S <- seat
  
  Rae_V[Rae_V < 0.5] <- NA
  Rae_S[Rae_S < 0.5] <- NA
  
  Dhondt_V[Dhondt_V < 0.5] <- NA
  Dhondt_S[Dhondt_S < 0.5] <- NA
  
  Index_list[["enp_vote"]]  <- 1 / sum((vote / 100)^2) # ENP (Vote)
  Index_list[["enp_seat"]]  <- 1 / sum((seat / 100)^2) # ENP (Seat)
  Index_list[["gallagher"]] <- sqrt(0.5 * sum((vote - seat)^2)) # Gallagher
  Index_list[["rose"]]      <- sum(abs(vote - seat)) * 0.5                # Rose
  Index_list[["rae"]]       <- mean(abs(Rae_V - Rae_S), na.rm = TRUE)     # Rae 
  Index_list[["sl"]]        <- sum((vote - seat)^2 / vote, na.rm  = TRUE) # SL
  Index_list[["dt"]]        <- max(seat / vote, na.rm = TRUE) # Dhondt
  Index_list[["dt5"]]       <- max(Dhondt_S / Dhondt_V, na.rm = TRUE) # Dhondt5
  
  class(Index_list) <- c("PRcalc_index", "list")
  
  Index_list
}

#' Print \code{PRcalc_index} Object
#'
#' @method print PRcalc_index
#'
#' @param x A \code{PRcalc_index} object
#' @param digits a integer
#' @param ... Ingnored
#'
#' @return
#' none
#' 
#' @export
#'
#' @examples
#' Election_Data1 <- data.frame(Party = c("Party A", "Party B", "Party C",
#'                                        "Party D", "Party E"),
#'                              Votes = c(778000, 714000, 331000, 299000, 230000))
#' Election_Data2 <- data.frame(Party   = c("Party A", "Party B", "Party C",
#'                                          "Party D", "Party E"),
#'                              Region1 = c(778000, 714000, 331000, 299000, 230000),
#'                              Region2 = c(1454000, 761000, 913000, 464000, 311000))
#' 
#' PR_example1 <- PRcalc(Election_Data1, seats = 8, method = "msl", threshold = 0)
#' PR_example2 <- PRcalc(Election_Data1, seats = 8, method = "msl", threshold = 0.1)
#' PR_example3 <- PRcalc(Election_Data2, seats = c(8, 13), method = "dt", threshold = 0)
#' 
#' PR_index1 <- index(PR_example1)
#' PR_index2 <- index(PR_example2)
#' PR_index3 <- index(PR_example3)
#' 
#' PR_index1
#' print(PR_index2, digits = 1)
#' PR_index3$gallagher # Gallagher非比例性指標のみ抽出
print.PRcalc_index <- function (x, digits = 3, ...) {
  
  result <- data.frame(
    Index = c("ENP (Vote)", "ENP (Seat)", "Gallagher", "Loosemore\u2013Hanby",
              "Rae", "Sainte\u2013Lagu\u00eb", "D\'Hondt", "D\'Hondt (5%)"),
    Value = sprintf(paste0("%.", digits, "f"), unlist(x))
  )
  
  print(result)
}
