# Generated by fusen: do not edit by hand

#' \code{PRcalc}オブジェクトの可視化
#'
#' @method plot PRcalc
#' 
#' @param x \code{PRcalc}オブジェクト
#' @param summary \code{TRUE}、または\code{FALSE} (既定値); \code{TRUE}の場合、ブロックごとのプロットが省略されます。
#' @param xlab 横軸のタイトル
#' @param ylab 縦軸のタイトル
#' @param text_size 文字の大きさ; 既定値は12
#' @param text_angle 横軸ラベルの角度; 既定値は0
#' @param ... Ingnored
#' 
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom tidyr separate
#' @importFrom tidyr pivot_longer
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 position_dodge
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 element_text
#' @importFrom forcats fct_inorder
#' @importFrom magrittr `%>%`
#'
#' @return
#' A \code{ggplot} object.
#' @export
#'
#' @examples
#' #| dev: "ragg_png"
#' #| fig.width: 7
#' #| out.width: 650
#' #| dpi: 300
#' Election_Data1 <- data.frame(Party = c("Party A", "Party B", "Party C",
#'                                        "Party D", "Party E"),
#'                              Votes = c(778000, 714000, 331000, 299000, 230000))
#' 
#' PR_example1 <- PRcalc(Election_Data1, seats = 8, method = "msl", threshold = 0)
#' 
#' plot(PR_example1) # PR_example1の可視化
plot.PRcalc <- function (x, 
                         summary    = FALSE, 
                         xlab       = "Party",
                         ylab       = "%",
                         text_size  = 12,
                         text_angle = 0, 
                         ...) {
  
  Party <- Type <- Share <- Region <- NULL
  vote <- seat <- temp_df <- NULL
  
  if (summary | x$N_Block == 1) {
    vote <- select(x$VoteShare, 1, TV = last_col())
    seat <- select(x$SeatShare, 1, TS = last_col())
    
    temp_df <- left_join(vote, seat, by = "Party") %>%
      pivot_longer(cols      = -Party,
                   names_to  = "Type",
                   values_to = "Share") %>%
      mutate(Type  = factor(Type, levels = c("TV", "TS"), 
                            labels = c("Total Vote", "Total Seat")),
             Share = Share)
  } else {
    temp_df <- left_join(x$VoteShare, x$SeatShare, by = "Party",
                         suffix = c("_V", "_S")) %>%
      pivot_longer(cols      = -Party,
                   names_to  = "Region",
                   values_to = "Share") %>%
      separate(Region, into = c("Region", "Type"), sep = "_") %>%
      mutate(Region = fct_inorder(Region)) %>%
      mutate(Type  = factor(Type, levels = c("V", "S"), 
                            labels = c("Vote Share", "Seat Share")),
             Share = Share) 
  }
  
  result_plot <- temp_df %>%
    mutate(Party = fct_inorder(Party)) %>%
    ggplot() +
    geom_bar(aes(x = Party, y = Share, fill = Type), 
             stat = "identity", position = position_dodge()) +
    labs(x = xlab, y = ylab, fill = "") +
    theme_bw(base_size = 12) +
    theme(legend.position = "bottom",
          axis.text.x     = element_text(angle = text_angle, 
                                         hjust = 1),
          text            = element_text(size  = text_size))
  
  if (summary | x$N_Block == 1) {
    return(result_plot)
  } else{
    return(result_plot + facet_wrap(~Region))
  }
}

#' \code{PRcalc}オブジェクトの可視化
#'
#' @method plot PRcalc
#' 
#' @param x \code{PRcalc}オブジェクト
#' @param summary \code{TRUE}、または\code{FALSE} (既定値); \code{TRUE}の場合、ブロックごとのプロットが省略されます。
#' @param xlab 横軸のタイトル
#' @param ylab 縦軸のタイトル
#' @param text_size 文字の大きさ; 既定値は12
#' @param text_angle 横軸ラベルの角度; 既定値は0
#' @param ... Ingnored
#' 
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom tidyr separate
#' @importFrom tidyr pivot_longer
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 position_dodge
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 element_text
#' @importFrom forcats fct_inorder
#' @importFrom magrittr `%>%`
#'
#' @return
#' A \code{ggplot} object.
#' @export
#'
#' @examples
#' #| dev: "ragg_png"
#' #| fig.width: 7
#' #| out.width: 650
#' #| dpi: 300
#' Election_Data2 <- data.frame(Party   = c("Party A", "Party B", "Party C",
#'                                          "Party D", "Party E"),
#'                              Region1 = c(778000, 714000, 331000, 299000, 230000),
#'                              Region2 = c(1454000, 761000, 913000, 464000, 311000))
#' 
#' PR_example2 <- PRcalc(Election_Data2, seats = c(8, 13), method = "dt", threshold = 0)
#' 
#' plot(PR_example2) # PR_example2の可視化
#' plot(PR_example2, text_angle = 25) # X軸ラベルの回転
#' plot(PR_example2, summary = TRUE) # ブロックごとの図を省略
plot.PRcalc <- function (x, 
                         summary    = FALSE, 
                         xlab       = "Party",
                         ylab       = "%",
                         text_size  = 12,
                         text_angle = 0, 
                         ...) {
  
  Party <- Type <- Share <- Region <- NULL
  vote <- seat <- temp_df <- NULL
  
  if (summary | x$N_Block == 1) {
    vote <- select(x$VoteShare, 1, TV = last_col())
    seat <- select(x$SeatShare, 1, TS = last_col())
    
    temp_df <- left_join(vote, seat, by = "Party") %>%
      pivot_longer(cols      = -Party,
                   names_to  = "Type",
                   values_to = "Share") %>%
      mutate(Type  = factor(Type, levels = c("TV", "TS"), 
                            labels = c("Total Vote", "Total Seat")),
             Share = Share)
  } else {
    temp_df <- left_join(x$VoteShare, x$SeatShare, by = "Party",
                         suffix = c("_V", "_S")) %>%
      pivot_longer(cols      = -Party,
                   names_to  = "Region",
                   values_to = "Share") %>%
      separate(Region, into = c("Region", "Type"), sep = "_") %>%
      mutate(Region = fct_inorder(Region)) %>%
      mutate(Type  = factor(Type, levels = c("V", "S"), 
                            labels = c("Vote Share", "Seat Share")),
             Share = Share) 
  }
  
  result_plot <- temp_df %>%
    mutate(Party = fct_inorder(Party)) %>%
    ggplot() +
    geom_bar(aes(x = Party, y = Share, fill = Type), 
             stat = "identity", position = position_dodge()) +
    labs(x = xlab, y = ylab, fill = "") +
    theme_bw(base_size = 12) +
    theme(legend.position = "bottom",
          axis.text.x     = element_text(angle = text_angle, 
                                         hjust = 1),
          text            = element_text(size  = text_size))
  
  if (summary | x$N_Block == 1) {
    return(result_plot)
  } else{
    return(result_plot + facet_wrap(~Region))
  }
}
