# Generated by fusen: do not edit by hand

#' Highest Average
#'
#' @param votes a data.frame or tibble with two columns. The first and second column represents names of parties and numbers of votes, respectively.
#' @param seat a numeric value of number of seats.
#' @param method a character string giving a method for computing seat allocation. This must be one of the strings "dt", "sl", "msl", "adams", "danish", "hh", "dean", or "imperiali".
#' @param threshold an optional numeric value of threshold. The  
#' @param region_name a character string.
#' 
#' @importFrom dplyr mutate
#' @importFrom dplyr select
#' @importFrom dplyr arrange
#' @importFrom dplyr desc
#' @importFrom dplyr group_by
#' @importFrom dplyr left_join
#' @importFrom dplyr summarise
#' @importFrom dplyr n
#' @importFrom dplyr case_when
#' @importFrom magrittr `%>%`
#' @importFrom utils head
#'
#' @return
#' A data.frame with two columns.
#' @export
#'
#' @examples
#' hae_example <- data.frame(Party = c("Party A", "Party B", "Party C", "Party D"),
#'                           Votes = c(53000, 25000, 16600, 5400))
#' 
#' hae_example
#' 
#' prcalc_hae(votes       = hae_example,
#'            seat        = 10,
#'            method      = "dt",
#'            threshold   = 0,
#'            region_name = "National")
prcalc_hae <- function(votes, 
                       seat, 
                       method      = c("dt", "sl", "msl", "adams", "danish", "hh", "dean", "imperiali"), 
                       threshold   = 0, 
                       region_name = "National") {
  
  Seat <- Vote <- Party <- Q <- Share <- NULL
  
  temp_votes        <- votes
  raw_votes         <- votes
  names(temp_votes) <- c("Party", "Vote")
  names(raw_votes)  <- c("Party", "Vote")
  
  temp_votes <- temp_votes %>%
    mutate(Share = Vote / sum(Vote),
           Vote  = ifelse(Share < threshold, 0, Vote))
  
  temp_votes <- temp_votes[rep(1:nrow(temp_votes), seat), ]
  
  R_n <- 0:(seat - 1)
  
  if (method == "dt") {
    # D'Hondt method
    R_n_vec <- R_n + 1
  } else if (method == "sl") {
    # Sainte-Laguë method
    R_n_vec <- seq(1, by = 2, length.out = seat)
  } else if (method == "msl") {
    # Modified Sainte-Laguë method
    R_n_vec <- seq(1, by = 2, length.out = seat)
    R_n_vec[1] <- 1.4
  } else if (method == "adams") {
    # Adams's method
    R_n_vec <- R_n
  } else if (method == "danish") {
    # Danish method
    R_n_vec <- seq(1, 3 * seat, by = 3)
  } else if (method == "hh") {
    # Huntington–Hill method
    R_n_vec <- sqrt(R_n * (R_n + 1))
  } else if (method == "dean") {
    # Dean method
    R_n_vec <- (2 * R_n * (R_n + 1)) / (2 * R_n + 1)
  } else if (method == "imperiali") {
    # Imperiali
    R_n_vec <- seq(1, by = 0.5, length.out = seat)
  }
  
  seat_df <- temp_votes %>% 
    mutate(R_n = rep(R_n_vec, each = nrow(votes)),
           Q   = Vote / R_n) %>%
    arrange(desc(Q)) %>%
    head(n = seat) %>%
    group_by(Party) %>%
    summarise(Seat    = n(),
              .groups = "drop") %>%
    as.data.frame()
  
  hae_result <- left_join(raw_votes, seat_df, by = "Party") %>%
    select(-Party) %>%
    mutate(Seat = ifelse(is.na(Seat), 0, Seat))
  
  names(hae_result) <- c(paste0(region_name, ":Vote"),
                         paste0(region_name, ":Seat"))
  
  hae_result
}
