# Generated by fusen: do not edit by hand

#' Block PR
#'
#' @param votes a data.frame or tibble with two columns. The first and second column represents names of parties and numbers of votes, respectively.
#' @param seat a numeric value of number of seats.
#' @param method a character string giving a method for computing seat allocation. This must be one of the strings "dt", "sl", "msl", "adams", "danish", "hh", "dean", or "imperiali".
#' @param threshold an optional numeric value of threshold. The  
#' 
#' @importFrom dplyr select
#' @importFrom dplyr bind_cols
#' @importFrom dplyr ends_with
#'
#' @return
#' A data.frame with two columns.
#' @export
#'
#' @examples
#' block_example <- data.frame(Party    = c("Party A", "Party B", "Party C", "Party D"),
#'                             Region_A = c(53000, 25000, 16600, 5400),
#'                             Region_B = c(12000, 34000, 5000, 10000),
#'                             Region_C = c(40000, 30000, 20000, 9000))
#' 
#' block_example
#' 
#' prcalc_block(votes       = block_example,
#'              seat        = c(10, 8, 11),
#'              method      = "dt",
#'              threshold   = 0)
prcalc_block <- function(votes, 
                         seat, 
                         method, 
                         threshold = 0) {
  
  Party <- NULL
  
  multi_result <- list()
  region_list  <- names(votes)[-1]
  
  if (length(region_list) == 1) {
    region_list <- "National"
  }
  
  LRM_methods <- c("hare", "droop", "imperialiQ")
  HAE_methods <- c("dt", "sl", "msl", "adams", "danish",
                   "hh", "dean", "imperiali")
  
  if (method %in% LRM_methods) {
    for (i in 1:length(region_list)) {
      temp_df <- votes[, c(1, i+1)]
      multi_result[[i]] <- prcalc_lrm(temp_df, seat[i], method, 
                                      threshold, region_list[i])
    }
  } else if (method %in% HAE_methods) {
    for (i in 1:length(region_list)) {
      temp_df <- votes[, c(1, i+1)]
      multi_result[[i]] <- prcalc_hae(temp_df, seat[i], method, 
                                      threshold, region_list[i])
    }
  }
  
  multi_result <- bind_cols(data.frame(Party = votes[, 1]),
                            bind_cols(multi_result))
  
  multi_result1 <- select(multi_result, Party, ends_with("Vote"))
  multi_result2 <- select(multi_result, Party, ends_with("Seat"))
  
  multi_result <- list(Vote = multi_result1, Seat = multi_result2)
  
  multi_result
}
