# Generated by fusen: do not edit by hand

#' 比例代表の議席割当計算
#'
#' @param x \code{data.frame}、または\code{tibble}オブジェクト
#' @param seats 議席数; 長さ1以上の\code{numeric}型ベクトル
#' @param method 議席割当方式;
#' @param threshold 阻止条項 (0 ~ 1); 既定値は0
#' 
#' @details
#' 各引数の詳細は以下の通りです。
#' \describe{
#' \item{\code{x}}{2列以上の\code{data.frame}、または\code{tibble}オブジェクトです。1列目は政党名、2列目以降は各ブロックにおける当該政党の得票数が入ります。}
#' \item{\code{seats}}{総議席数。全国区で50議席の場合は\code{seats = 50}、3ブロックで議席数がそれぞれ10、20、30の場合は\code{seats = c(10, 20, 30)}のように指定します。}
#' \item{\code{method}}{
#' 議席割当方式
#' \itemize{
#' \item{\code{"dt"}: ドント方式 (d’Hondt / Jefferson)}
#' \item{\code{"sl"}: サン＝ラゲ方式 (Sainte-Laguë / Webster)}
#' \item{\code{"msl"}: 修正サン＝ラゲ方式 (Modified Sainte-Laguë)}
#' \item{\code{"denmark"}: デンマーク方式 (Danish)}
#' \item{\code{"adams"}: アダムス方式 (Adams)}
#' \item{\code{"imperiali"}: インペリアリ方式 (Imperiali)}
#' \item{\code{"hh"}: ハンチントン＝ヒール方式 (Huntington-Hill)}
#' \item{\code{"dean"}: ディーン方式 (Dean)}
#' \item{\code{"hare"}: ヘア＝ニーマイヤー方式 (Hare-Niemeyer)}
#' \item{\code{"droop"}: ドループ方式 (Droop)}
#' \item{\code{"imperialiQ"}: インペリアリ・クオタ―方式 (Imperiali Quota)}
#' }
#' }
#' \item{\code{threshold}}{阻止条項。既定値は0ですが、例えば得票率が2%未満の政党に議席を割り当てない場合は\code{threshold = 0.02}のように指定します。}
#' }
#' 
#' @importFrom dplyr case_when
#' @importFrom purrr map_df
#' @importFrom stringr str_replace
#'
#' @return
#' \code{PRcalc}型オブジェクト
#' \describe{
#' \item{\code{Vote}}{得票数}
#' \item{\code{Seat}}{獲得議席数}
#' \item{\code{VoteShare}}{得票率}
#' \item{\code{SeatShare}}{獲得議席率}
#' \item{\code{N_Seat}}{各ブロックの議席数および総議席数}
#' \item{\code{N_Block}}{ブロック数}
#' \item{\code{threshold}}{阻止条項の閾値}
#' \item{\code{method}}{議席割当方式}
#' }
#' 
#' @seealso
#' \code{\link{print.PRcalc}}, \code{\link{summary.PRcalc}}, \code{\link{index.PRcalc}}, \code{\link{compare.PRcalc}}, \code{\link{plot.PRcalc}}
#' 
#' @export
#'
#' @examples
#' \donttest{
#' data(jp_upper_2019)
#' PRcalc(jp_upper_2019, seats = 50, method = "dt")
#' 
#' data(jp_lower_2021)
#' japan_2021 <- PRcalc(jp_lower_2021, method = "hare",
#'                      seats = c(8, 14, 20, 21, 17, 11, 21, 30, 11, 6, 21))
#' print(japan_2021)
#' print(japan_2021, prop = TRUE, digits = 1)
#' summary(japan_2021)
#' plot(japan_2021)
#' }
PRcalc <- function (x, 
                    seats, 
                    method, 
                    threshold = 0) {
  
  method_list <- c("hare", "droop", "imperialiQ", "dt", 
                   "sl", "msl", "adams", "danish", "hh", 
                   "dean", "imperiali")
  
  if (!(method %in% method_list)) {
    stop("Invalid allocation method. Please see ?PRcalc")
  }
  if (threshold < 0 | threshold >= 1) {
    stop("Invalid threshold (0 > threshold >= 0)")
  }
  
  seat_vec <- seats
  temp_df  <- x
  
  PRcalc_Result <- prcalc_block(votes = temp_df, seat = seat_vec,
                                method = method, threshold = threshold)
  
  VS_df <- PRcalc_Result$Vote
  SS_df <- PRcalc_Result$Seat
  
  if (ncol(VS_df) > 2 & ncol(SS_df) > 2) {
    PRcalc_Result$Vote$Total <- rowSums(PRcalc_Result$Vote[, -1])
    PRcalc_Result$Seat$Total <- rowSums(PRcalc_Result$Seat[, -1])
    VS_df$Total <- rowSums(VS_df[, -1])
    SS_df$Total <- rowSums(SS_df[, -1])  
  }
  
  if (ncol(VS_df) == 2 & ncol(SS_df) == 2) {
    VS_df[, -1] <- VS_df[, -1] / sum(VS_df[, -1]) * 100
    SS_df[, -1] <- SS_df[, -1] / sum(SS_df[, -1]) * 100
  } else if (ncol(VS_df) > 2 & ncol(SS_df) > 2) {
    VS_df[, -1] <- as.data.frame(map_df(VS_df[, -1], ~(.x / sum(.x) * 100)))
    SS_df[, -1] <- as.data.frame(map_df(SS_df[, -1], ~(.x / sum(.x) * 100)))
  }
  
  names(PRcalc_Result$Vote) <- str_replace(names(PRcalc_Result$Vote), ":Vote", "")
  names(PRcalc_Result$Seat) <- str_replace(names(PRcalc_Result$Seat), ":Seat", "")
  names(VS_df) <- str_replace(names(VS_df), ":Vote", "")
  names(SS_df) <- str_replace(names(SS_df), ":Seat", "")
  
  Method_full_name <- case_when(method == "hare" ~ "Hare\u2013Niemeyer",
                                method == "droop" ~ "Droop",
                                method == "imperialiQ" ~ "Imperiali Quota",
                                method == "dt" ~ "D\'Hondt (Jefferson)",
                                method == "sl" ~ "Sainte\u2013Lagu\u00eb (Webster)",
                                method == "msl" ~ "Modified Sainte\u2013Lagu\u00eb",
                                method == "hh" ~ "Huntington\u2013Hill",
                                method == "danish" ~ "Danish",
                                method == "adams" ~ "Adams\'s",
                                method == "imperiali" ~ "Imperiali",
                                method == "dean" ~ "Dean")
  
  PRcalc_Result <- list(Vote = PRcalc_Result$Vote,
                        Seat = PRcalc_Result$Seat,
                        VoteShare = VS_df,
                        SeatShare = SS_df,
                        N_Seat    = c(seats, sum(seats)),
                        N_Block   = length(seats),
                        threshold = threshold,
                        Method    = Method_full_name)
  
  class(PRcalc_Result) <- c("PRcalc", "list")
  
  return(structure(PRcalc_Result, class = c("PRcalc", "list")))
}

#' Print \code{PRclac} Object
#'
#' @method print PRcalc
#'
#' @param x \code{PRcalc} object
#' @param prop a logical value
#' @param digits a integer
#' @param ... Ingnored
#' 
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr across
#'
#' @return
#' none
#' 
#' @export
#'
print.PRcalc <- function (x, prop = FALSE, digits = 3, ...) {
  
  Party <- NULL
  
  if (prop == FALSE) {
    result <- left_join(x$Vote, x$Seat, by = "Party",
                        suffix = c("_V", "_S"))
  } else if (prop == TRUE) {
    temp_vote <- mutate(x$VoteShare, 
                        across(.cols = -Party, 
                               ~sprintf(paste0("%.", digits, "f"), .x)))
    temp_seat <- mutate(x$SeatShare, 
                        across(.cols = -Party, 
                               ~sprintf(paste0("%.", digits, "f"), .x)))
    result <- left_join(temp_vote, temp_seat, by = "Party",
                        suffix = c("_V", "_S"))
  }
  
  print(result)
}

#' Summarise \code{PRclac} Object
#'
#' @method summary PRcalc
#'
#' @param object \code{PRcalc} object
#' @param prop a logical value
#' @param digits a integer
#' @param ... Ingnored
#' 
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr last_col
#' @importFrom dplyr across
#'
#' @return
#' A data.frame
#' 
#' @export
#'
summary.PRcalc <- function (object, prop = FALSE, digits = 3, ...) {
  
  result <- vote <- seat <- NULL
  
  if (prop == FALSE) {
    vote <- select(object$Vote, 1, Total_Vote = last_col())
    seat <- select(object$Seat, 1, Total_Seat = last_col())
    
    result <- left_join(vote, seat, by = "Party")
  } else if (prop == TRUE) {
    vote <- select(object$VoteShare, 1, Total_Vote = last_col())
    seat <- select(object$SeatShare, 1, Total_Seat = last_col())

    result <- left_join(vote, seat, by = "Party")
    
    result <- mutate(result, 
                     across(.cols = -1, 
                            ~sprintf(paste0("%.", digits, "f"), .x)))
  }
  
  print(result)
}
