# Generated by fusen: do not edit by hand

#' PR Calculation
#'
#' @param x a \code{data.frame} or \code{tibble} object. 
#' @param seats 議席数; 長さ1以上の\code{numeric}型ベクトル
#' @param method 議席割当方式;
#' @param threshold a numeric value
#' 
#' @importFrom dplyr case_when
#' @importFrom purrr map_df
#' @importFrom stringr str_replace
#'
#' @return
#' A \code{list} type object.
#' @export
#'
PRcalc <- function (x, 
                    seats, 
                    method, 
                    threshold = 0) {
  
  method_list <- c("hare", "droop", "imperialiQ", "dt", 
                   "sl", "msl", "adams", "danish", "hh", 
                   "dean", "imperiali")
  
  if (!(method %in% method_list)) {
    stop("Invalid allocation method. Please see ?PRcalc")
  }
  if (threshold < 0 | threshold >= 1) {
    stop("Invalid threshold (0 > threshold >= 0)")
  }
  
  seat_vec <- seats
  temp_df  <- x
  
  PRcalc_Result <- prcalc_block(votes = temp_df, seat = seat_vec,
                                method = method, threshold = threshold)
  
  VS_df <- PRcalc_Result$Vote
  SS_df <- PRcalc_Result$Seat
  
  if (ncol(VS_df) > 2 & ncol(SS_df) > 2) {
    PRcalc_Result$Vote$Total <- rowSums(PRcalc_Result$Vote[, -1])
    PRcalc_Result$Seat$Total <- rowSums(PRcalc_Result$Seat[, -1])
    VS_df$Total <- rowSums(VS_df[, -1])
    SS_df$Total <- rowSums(SS_df[, -1])  
  }
  
  if (ncol(VS_df) == 2 & ncol(SS_df) == 2) {
    VS_df[, -1] <- VS_df[, -1] / sum(VS_df[, -1]) * 100
    SS_df[, -1] <- SS_df[, -1] / sum(SS_df[, -1]) * 100
  } else if (ncol(VS_df) > 2 & ncol(SS_df) > 2) {
    VS_df[, -1] <- as.data.frame(map_df(VS_df[, -1], ~(.x / sum(.x) * 100)))
    SS_df[, -1] <- as.data.frame(map_df(SS_df[, -1], ~(.x / sum(.x) * 100)))
  }
  
  names(PRcalc_Result$Vote) <- str_replace(names(PRcalc_Result$Vote), ":Vote", "")
  names(PRcalc_Result$Seat) <- str_replace(names(PRcalc_Result$Seat), ":Seat", "")
  names(VS_df) <- str_replace(names(VS_df), ":Vote", "")
  names(SS_df) <- str_replace(names(SS_df), ":Seat", "")
  
  Method_full_name <- case_when(method == "hare" ~ "Hare\u2013Niemeyer",
                                method == "droop" ~ "Droop",
                                method == "imperialiQ" ~ "Imperiali Quota",
                                method == "dt" ~ "D\'Hondt (Jefferson)",
                                method == "sl" ~ "Sainte\u2013Lagu\u00eb (Webster)",
                                method == "msl" ~ "Modified Sainte\u2013Lagu\u00eb",
                                method == "hh" ~ "Huntington\u2013Hill",
                                method == "danish" ~ "Danish",
                                method == "adams" ~ "Adams\'s",
                                method == "imperiali" ~ "Imperiali",
                                method == "dean" ~ "Dean")
  
  PRcalc_Result <- list(Vote = PRcalc_Result$Vote,
                        Seat = PRcalc_Result$Seat,
                        VoteShare = VS_df,
                        SeatShare = SS_df,
                        N_Seat    = c(seats, sum(seats)),
                        N_Block   = length(seats),
                        threshold = threshold,
                        Method    = Method_full_name)
  
  class(PRcalc_Result) <- c("PRcalc", "list")
  
  return(structure(PRcalc_Result, class = c("PRcalc", "list")))
}

#' Print \code{PRclac} Object
#'
#' @method print PRcalc
#'
#' @param x \code{PRcalc} object
#' @param prop a logical value
#' @param digits a integer
#' @param ... Ingnored
#' 
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr across
#'
#' @return
#' A data.frame
#' 
#' @export
#'
print.PRcalc <- function (x, prop = FALSE, digits = 3, ...) {
  
  Party <- NULL
  
  if (prop == FALSE) {
    result <- left_join(x$Vote, x$Seat, by = "Party",
                        suffix = c("_V", "_S"))
  } else if (prop == TRUE) {
    temp_vote <- mutate(x$VoteShare, 
                        across(.cols = -Party, 
                               ~sprintf(paste0("%.", digits, "f"), .x)))
    temp_seat <- mutate(x$SeatShare, 
                        across(.cols = -Party, 
                               ~sprintf(paste0("%.", digits, "f"), .x)))
    result <- left_join(temp_vote, temp_seat, by = "Party",
                        suffix = c("_V", "_S"))
  }
  
  print(result)
}

#' Summarise \code{PRclac} Object
#'
#' @method summary PRcalc
#'
#' @param object \code{PRcalc} object
#' @param prop a logical value
#' @param digits a integer
#' @param ... Ingnored
#' 
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr last_col
#' @importFrom dplyr across
#'
#' @return
#' A data.frame
#' 
#' @export
#'
summary.PRcalc <- function (object, prop = FALSE, digits = 3, ...) {
  
  result <- vote <- seat <- NULL
  
  if (prop == FALSE) {
    vote <- select(object$Vote, 1, Total_Vote = last_col())
    seat <- select(object$Seat, 1, Total_Seat = last_col())
    
    result <- left_join(vote, seat, by = "Party")
  } else if (prop == TRUE) {
    vote <- select(object$VoteShare, 1, Total_Vote = last_col())
    seat <- select(object$SeatShare, 1, Total_Seat = last_col())

    result <- left_join(vote, seat, by = "Party")
    
    result <- mutate(result, 
                     across(.cols = -1, 
                            ~sprintf(paste0("%.", digits, "f"), .x)))
  }
  
  print(result)
}
