# Generated by fusen: do not edit by hand

#' Largest Remainder Method
#'
#' @param votes a data.frame or tibble with two columns. The first and second column represents names of parties and numbers of votes, respectively.
#' @param seat a numeric value of number of seats.
#' @param method a character string giving a method for computing seat allocation. This must be one of the strings "hare", "droop", or "imperialiQ".
#' @param threshold an optional numeric value of threshold. The  
#' @param region_name a character string.
#' 
#' @importFrom dplyr mutate
#' @importFrom dplyr select
#' @importFrom dplyr case_when
#' @importFrom magrittr `%>%`
#'
#' @return
#' A data.frame with two columns.
#' @export
#'
#' @examples
#' lrm_example <- data.frame(Party = c("Party A", "Party B", "Party C", "Party D"),
#'                           Votes = c(53000, 25000, 16600, 5400))
#' 
#' lrm_example
#' 
#' prcalc_lrm(votes       = lrm_example,
#'            seat        = 10,
#'            method      = "hare",
#'            threshold   = 0,
#'            region_name = "National")
prcalc_lrm <- function(votes, 
                       seat, 
                       method = c("hare", "droop", "imperialiQ"),
                       threshold = 0, 
                       region_name) {
  
  Seat <- Seat1 <- Seat2 <- Seat3 <- Seat4 <- Vote <- Vote2 <- Q <- Share <- NULL
  
  temp_votes        <- votes
  names(temp_votes) <- c("Party", "Vote")
  
  result <- temp_votes %>%
    mutate(
      Share = Vote / sum(Vote),
      Vote2 = ifelse(Share < threshold, NA, Vote),
      Total = sum(Vote2, na.rm = TRUE),
      Q     = case_when(method == "hare" ~ Total / seat,
                        method == "droop" ~ floor(1 + (Total / (1 + seat))),
                        method == "imperialiQ" ~ Total / (2 + seat)),
      Seat1 = floor(Vote2 / Q),
      Seat2 = 1 - ((Vote2 / Q) - floor(Vote2 / Q)),
      Seat3 = rank(Seat2),
      Seat4 = ifelse(Seat3 <= (seat - sum(Seat1, na.rm = TRUE)), 1, 0),
      Seat  = Seat1 + Seat4
    ) %>%
    select(Vote, Seat) %>%
    mutate(Seat = ifelse(is.na(Seat), 0, Seat))
  
  names(result) <- c(paste0(region_name, ":Vote"),
                     paste0(region_name, ":Seat"))
  
  result
}
